import CardListLayout from '@/components/ui/CardListLayout/CardListLayout';
import PublicLayout from '@/components/ui/PublicLayout';
import AgenciesContainer from '@/components/ui/agencies/AgenciesContainer';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Agencies | Next Adventure',
	description: 'Generated by create next app',
};

const Agencies = () => {
	return (
		<>
			<PublicLayout>
				<div className='extra_large_layout'>
					<CardListLayout
						title="AGENCIES"
						description="Discover your tour planner and transform your journey into an unforgettable adventure."
					>
						<AgenciesContainer />
					</CardListLayout>
				</div>
			</PublicLayout>
		</>
	);
};

export default Agencies;
