import ProtectedWithAuth from '@/components/protectedRoute/ProtectedRoute';
import PlanDetail from '@/components/ui/PlanDetails/PlanDetails';
import { Metadata } from 'next';

type IDProps = {
	params: any;
};

export const metadata: Metadata = {
	title: 'Details | Plan | Next Adventure',
	description: 'Generated by create next app',
};

const PlanDetails = ({ params }: IDProps) => {
	return (
		<ProtectedWithAuth>
			<PlanDetail id={params.id} />
		</ProtectedWithAuth>
	);
};

export default PlanDetails;
