import ProtectedWithAuth from '@/components/protectedRoute/ProtectedRoute';
import PublicLayout from '@/components/ui/PublicLayout';
import AgencyDetailsCompo from '@/components/ui/agencyDetails/AgencyDetails';
import { Metadata } from 'next';

type IDProps = {
	params: any;
};

export const metadata: Metadata = {
	title: 'Details | Agency | Next Adventure',
	description: 'Generated by create next app',
};

const AgencyDetails = ({ params }: IDProps) => {
	return (
		<PublicLayout>
			<ProtectedWithAuth>
				<div style={{ margin: '10px' }}>
					<AgencyDetailsCompo id={params.id} />
				</div>
			</ProtectedWithAuth>
		</PublicLayout>
	);
};

export default AgencyDetails;
