import Providers from '@/lib/Providers'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ConfigProvider } from 'antd'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <ConfigProvider
      theme={{
    components: {
      Input: {
        activeBg: 'white',
        hoverBg:'rgb(229, 235, 240)'
          },
          Button: {
        fontWeight:500
      }
          },
          token: {
          colorPrimary:'#088345'
        }
  }}
      >
      <html lang="en">
      <body className={inter.className}>{children}</body>
        </html>
        </ConfigProvider>
    </Providers>
  )
}
