import PublicLayout from '@/components/ui/PublicLayout';
import Hero from '@/components/ui/landing-page/Banners/Hero-Section/Hero';
import LandingPageProvider from '@/components/ui/landing-page/LandingPageProvider/LandingPageProvider';
import { Content } from 'antd/es/layout/layout';
import { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Home | Next Adventure',
	description: 'Generated by create next app',
};

export default function Home() {
	return (
		<PublicLayout>
			<Hero />
			<Content>
				<LandingPageProvider />
			</Content>
		</PublicLayout>
	);
}
